### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by imranismail**
Minor nitpick, btw great job!

### CODE REVIEW

**Comment by mindreframer** [comment]
:) Thanks! LOL - RAILSway.... Rails-driven development got deep into my system, must reprogram! ;) BTW: really liking your https://github.com/imranismail/phoenix_webpack generator! I was banging my head on webpack that stayed running in the background after phoenix quit and then I have found your PR: https://github.com/webpack/webpack-dev-server/pull/352 ! :+1: So simple and useful!

**Comment by imranismail** [comment]
Thanks! I should probably update it to the latest phoenix and use that merged PR.

**Comment by mindreframer** [comment]
@imranismail btw, I'm building up a collection of small useful libraries to solve practical problems when implementing real Elixir apps. My motivation is to start an Elixir consulting agency with a remote team later, when Elixir wins more developers / market mindshare (it's only a question of time). I like your code style and I think we could have a fruitful collaboration, if you're interested. 

My next small library is https://github.com/ruby2elixir/plugin - a slimmed down version of plug for general purpose programs (outside of web response/request cycle). I'm finishing an article right now introducing it and will publish it in a couple of days. My background is Rails dev since 2007 with high accent on DevOps / High Reliability. Last 2 years I've spend doing mostly frontend with React.js. So... 

I'm looking for self-motivated people who'd like to use Elixir as a platform for their future apps. My gut feeling tells me that many of the current Rails apps will be converted to Elixir in the next 3-5 years, and many new apps that would be perfect candidates for Rails will instead pick Elixir as starting foundation. 

I really enjoy working with Elixir and see a tremendous value in provided OTP platform and functional paradigm. What I need now are motivated trustworthy partners / freelancers with ambitions and great work ethics. :) I'm a workaholic and expect my team members to support our work and not just enjoy the "free-ride". 

Your article https://127labs.com/what-ive-learned-so-far-from-functional-programming/ resonated quite with my own experience: 
- functional programming patterns are making code more reliable and predictable (very desired qualities of real life programs) 

Would you be interested in collaborating on "ruby2elixir" github-team and also on http://ruby2elixir.github.io/ blog and https://twitter.com/ruby2elixir  twitter account? ;) 

The short-term goal is to promote Elixir and make it more accessible for current Ruby developers. I had a bad start with some probably stupid blog articles comparing code quality by the number of github issues... Was not recieved very well ;)) But I plan to write more useful guides comparing Rails / Elixir side-by-side to provide a smooth experience moving Rails apps to Elixir. 

Would that be interesting for you? 

Cheers, 
Roman

**Comment by imranismail** [comment]
Hey @mindreframer,

I humbly accept your offer, I have the same gut feeling as well and your thoughts on Elixir resonates loudly with mine, It's just a matter of time. Perhaps this could serve as a good opportunity for me to build the community and introduce Elixir in my country as well.

I really enjoy learning it and I want people to realize how difficult problems commonly known to distributed apps can be solved so easily by leveraging the Erlang VM and the OTP, not to mention using the explicitness and beauty of Elixir.

Elixir has a lot to offer and I want to share it.

Cheers,
Imran

**Comment by mindreframer** [comment]
Hey Imran, 

awesome! Thanks a lot, I'm sure we will have fun! ;) I've added you to the github team and also to the trello team. Currently it has little structure, but I have made very good experience with Trello for team communication and I think this will be a better tool than emailing things around for strategic discussions. 

I see you're working on https://github.com/imranismail/sentry/. Would you like me help there? I think it could be a great library! 

See you later, going to bed soon. 

BTW: we can continue talking per email: roman.heinrich@gmail.com

**Comment by imranismail** [comment]
That would be great! I need helpful input on that. I've tried a couple of stuff, but still it's not as simple as i want it to be.

**Pull request merged**
